server:
  port: "8089"

databases:
  - name: "game"
    shard_id: 0
    host: "localhost"
    port: "3306"
    user: "root"
    password: "npb@future"
    dbname: "FUTURE_NPB_GAME"
  - name: "shard_1"
    shard_id: 10
    host: "localhost"
    port: "3306"
    user: "root"
    password: "npb@future"
    dbname: "FNPB_GAME_S0"

redis:
  - name: "lock"
    host: "localhost"
    port: "6379"
    password: "npb@future"
    db: 0
  - name: "user_cache"
    host: "localhost"
    port: "6379"
    password: "npb@future"
    db: 1
  - name: "club_cache"
    host: "localhost"
    port: "6379"
    password: "npb@future"
    db: 2
  - name: "reload_pubsub"
    host: "localhost"
    port: "6379"
    password: "npb@future"
    db: 3

cdn:
  design_base_url: "https://futurenpb-dev-server-01.qpyou.cn:8001/test/design"
  http_timeout_seconds: 10
