syntax = "proto3";

package proto;
option go_package = "future_cpbl_web_server/pb";

message CardData {
  uint64 idx = 1;
  uint64 user_id = 2;
  uint32 card_id = 3;
  uint64 two_way_idx = 4;
  uint32 level_break_step = 5;
  uint32 level_break_cur_material = 6;
  uint32 limit_break_level = 7;
  uint32 limit_break_exp = 8;
  uint32 level = 9;
  uint32 exp = 10;
  uint32 exp_exceed = 11;
  uint32 theme_id = 12;
  uint32 extra_theme_id = 13;
  uint32 is_lock = 14;
  repeated SkillData skill = 15;
  map<uint32, uint32> potential_list = 16;
  uint64 enhance_card_idx = 17;
}

message SkillData {
  uint32 exp = 1;
  uint32 slot = 2;
  uint32 level = 3;
  uint32 skill_id = 4;
}

message GetCardsRequest {
}

message GetCardsResponse {
  repeated CardData cards = 1;
}

message UpgradeCardLevelRequest {
  uint64 card_idx = 1;
}

message UpgradeCardLevelResponse {
  CardData card = 1;
}