#!/usr/bin/env python3
"""Excel → Go struct 코드 생성 도구.

input 디렉토리의 xlsx 파일들을 읽어 디자인 데이터용 Go struct를 자동 생성한다.

사용법:
  python excel2struct.py [--input-dir DIR] [--output-dir DIR] [--package PKG]

기본값:
  --input-dir   ./input
  --output-dir  ./output
  --package     design

처리 대상:
  input/ 디렉토리의 모든 .xlsx 파일을 자동 처리한다.
  예: input/cards.xlsx → output/card_design.go
      type CardDesign struct { ... }

규칙:
  - 파일명(stem)을 PascalCase로 변환 후 'Design' 접미사 붙임
    cards.xlsx → CardDesign
    skills.xlsx → SkillDesign
    BAT_DATA.xlsx → BatDataDesign
  - 첫 시트 사용. 첫 행은 헤더(컬럼명).
  - 첫 번째 컬럼은 PK로 표시 (주석)
  - 각 컬럼명을 PascalCase Go 필드명으로 변환
  - 타입 추론: 정수→uint32, 큰정수→uint64, 실수→float64, 그 외→string
  - JSON 태그 자동 부여 (원본 컬럼명 그대로)
  - 임시 파일(~$로 시작), 숨김 파일은 제외

생성된 .go 파일은 internal/design/ 등으로 복사하여 사용한다.
"""

import argparse
import re
import sys
from pathlib import Path

try:
    import pandas as pd
except ImportError:
    print("pandas가 필요합니다. 'pip install pandas openpyxl'으로 설치하세요.", file=sys.stderr)
    sys.exit(1)


def list_xlsx_files(input_dir: Path) -> list[Path]:
    """input 디렉토리의 모든 xlsx 파일을 반환한다 (임시/숨김 제외)."""
    files = []
    for p in sorted(input_dir.glob("*.xlsx")):
        if p.name.startswith("~$") or p.name.startswith("."):
            continue
        files.append(p)
    return files


def to_pascal_case(name: str) -> str:
    """snake_case / kebab-case / UPPER_SNAKE → PascalCase."""
    parts = re.split(r"[_\-\s]+", name)
    return "".join(p.capitalize() for p in parts if p)


def to_go_field_name(col: str) -> str:
    """컬럼명을 Go 공개 필드명으로 변환한다.

    숫자로 시작하는 컬럼(예: 2B, 3B)은 Go 식별자 규칙상 그대로 사용할 수 없으므로
    'F' (Field) prefix를 붙인다. (2B → F2B, 3B → F3B)
    """
    pascal = to_pascal_case(col)
    if pascal and pascal[0].isdigit():
        pascal = "F" + pascal
    return pascal


def to_snake_case_filename(pascal: str) -> str:
    """PascalCase → snake_case (출력 파일명용)."""
    s = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", pascal)
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s)
    return s.lower()


def go_type_for_series(series) -> str:
    """pandas Series의 dtype으로 Go 타입을 추론한다.

    - 정수 (모든 값이 uint32 범위 내) → uint32
    - 정수 (큰 값 또는 음수 가능) → int64
    - 실수 → float64
    - 불린 → bool
    - 그 외 → string
    """
    s = series.dropna()
    if s.empty:
        return "string"

    if pd.api.types.is_bool_dtype(s):
        return "bool"

    if pd.api.types.is_integer_dtype(s):
        # 모두 0 이상이고 uint32 범위 내면 uint32
        if (s >= 0).all() and (s <= 0xFFFFFFFF).all():
            return "uint32"
        return "int64"

    if pd.api.types.is_float_dtype(s):
        # 정수처럼 보이는 float (1.0, 2.0 등)도 정수로 처리할지?
        # 안전하게 float64 유지
        return "float64"

    return "string"


def derive_type_name(stem: str) -> str:
    """파일명 stem → Go 타입명 (PascalCase + 'Design' 접미사)."""
    base = to_pascal_case(stem)
    if not base.endswith("Design"):
        base += "Design"
    return base


def render_struct(type_name: str, columns: list[tuple[str, str]], pk_column: str) -> str:
    """Go struct 코드 문자열을 생성한다.

    columns: [(원본_컬럼명, go_타입), ...]
    pk_column: 첫 번째 컬럼명 (PK 표시용)
    """
    # 컬럼명 → Go 필드명 폭 맞춤
    field_specs = []
    max_field_len = 0
    max_type_len = 0
    for col, gotype in columns:
        field = to_go_field_name(col)
        field_specs.append((field, gotype, col))
        max_field_len = max(max_field_len, len(field))
        max_type_len = max(max_type_len, len(gotype))

    lines = [f"type {type_name} struct {{"]
    for field, gotype, col in field_specs:
        pad_field = " " * (max_field_len - len(field) + 1)
        pad_type = " " * (max_type_len - len(gotype) + 1)
        comment = "  // PK" if col == pk_column else ""
        lines.append(f"\t{field}{pad_field}{gotype}{pad_type}`json:\"{col}\"`{comment}")
    lines.append("}")
    return "\n".join(lines)


def render_file(package: str, type_name: str, struct_body: str, source_file: str) -> str:
    """완성된 .go 파일 문자열을 생성한다."""
    return (
        f"// Code generated by excel2struct from {source_file}. DO NOT EDIT.\n"
        f"package {package}\n\n"
        f"{struct_body}\n"
    )


def is_empty_column_name(col) -> bool:
    """헤더 셀이 비어있는 컬럼인지 판별한다.

    pandas는 빈 헤더 셀을 'Unnamed: N' 형태로 자동 채우거나 NaN으로 둔다.
    둘 다 제외 대상.
    """
    if col is None:
        return True
    if isinstance(col, float) and pd.isna(col):
        return True
    s = str(col).strip()
    if not s:
        return True
    if s.startswith("Unnamed:"):
        return True
    return False


def process(xlsx_path: Path, output_dir: Path, package: str) -> Path:
    """xlsx 한 파일을 처리하여 .go 파일을 생성한다. 출력 경로 반환."""
    df = pd.read_excel(xlsx_path, sheet_name=0)
    if df.empty or len(df.columns) == 0:
        raise ValueError(f"{xlsx_path}: 컬럼 없음")

    columns: list[tuple[str, str]] = []
    for col in df.columns:
        if is_empty_column_name(col):
            continue
        gotype = go_type_for_series(df[col])
        columns.append((str(col), gotype))

    if not columns:
        raise ValueError(f"{xlsx_path}: 유효한 컬럼이 없음")

    # 빈 컬럼 제외 후 첫 번째가 PK
    pk_col = columns[0][0]

    type_name = derive_type_name(xlsx_path.stem)
    struct_body = render_struct(type_name, columns, pk_col)
    content = render_file(package, type_name, struct_body, xlsx_path.name)

    out_path = output_dir / f"{to_snake_case_filename(type_name)}.go"
    out_path.write_text(content, encoding="utf-8")
    return out_path


def main():
    parser = argparse.ArgumentParser(description="Excel → Go struct 코드 생성 도구")
    parser.add_argument("--input-dir", default="input", help="xlsx 입력 디렉토리")
    parser.add_argument("--output-dir", default="output", help=".go 출력 디렉토리")
    parser.add_argument("--package", default="design", help="생성된 파일의 Go 패키지명")
    args = parser.parse_args()

    input_dir = Path(args.input_dir)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    if not input_dir.is_dir():
        print(f"input 디렉토리가 존재하지 않습니다: {input_dir}", file=sys.stderr)
        sys.exit(1)

    xlsx_files = list_xlsx_files(input_dir)
    if not xlsx_files:
        print(f"xlsx 파일이 없습니다: {input_dir}", file=sys.stderr)
        sys.exit(1)

    for xlsx_path in xlsx_files:
        try:
            out_path = process(xlsx_path, output_dir, args.package)
            print(f"ok: {xlsx_path} → {out_path}")
        except Exception as e:
            print(f"err: {xlsx_path}: {e}", file=sys.stderr)


if __name__ == "__main__":
    main()
