// Code generated by excel2struct from BAT_DATA.xlsx. DO NOT EDIT.
package schema

type BatDataDesign struct {
	Idx            int32  `json:"IDX"`
	Nid            int32  `json:"NID"`  // PK
	LbNumber       uint64 `json:"LB_NUMBER"`
	Useflag        bool   `json:"USEFLAG"`
	Season         int32  `json:"SEASON"`
	Team           int32  `json:"TEAM"`
	FullName       string `json:"FULL_NAME"`
	BasePosition   int32  `json:"BASE_POSITION"`
	SubPosition    int32  `json:"SUB_POSITION"`
	Bats           int32  `json:"BATS"`
	Throws         int32  `json:"THROWS"`
	LbId           int32  `json:"LB_ID"`
	Rarity         int32  `json:"RARITY"`
	Kind           int32  `json:"KIND"`
	Ovr            int32  `json:"OVR"`
	Power          int32  `json:"POWER"`
	Contact        int32  `json:"CONTACT"`
	Vision         int32  `json:"VISION"`
	Discipline     int32  `json:"DISCIPLINE"`
	RunningSpeed   int32  `json:"RUNNING_SPEED"`
	Fielding       int32  `json:"FIELDING"`
	Ala            int32  `json:"ALA"`
	Edition        int32  `json:"EDITION"`
	FullSwing      int32  `json:"FULL_SWING"`
	Clutch         int32  `json:"CLUTCH"`
	Steal          int32  `json:"STEAL"`
	Bunt           int32  `json:"BUNT"`
	Throw          int32  `json:"THROW"`
	Defense        int32  `json:"DEFENSE"`
	Running        int32  `json:"RUNNING"`
	VsUp           int32  `json:"VS_UP"`
	VsDown         int32  `json:"VS_DOWN"`
	VsIn           int32  `json:"VS_IN"`
	VsOut          int32  `json:"VS_OUT"`
	VsPitL         int32  `json:"VS_PIT_L"`
	VsPitR         int32  `json:"VS_PIT_R"`
	VsFb           int32  `json:"VS_FB"`
	VsBb           int32  `json:"VS_BB"`
	VsOsb          int32  `json:"VS_OSB"`
	GbHitter       int32  `json:"GB_HITTER"`
	FbHitter       int32  `json:"FB_HITTER"`
	FranchiseBat   int32  `json:"FRANCHISE_BAT"`
	ExclusiveTheme int32  `json:"EXCLUSIVE_THEME"`
	TwoWay         int32  `json:"TWO_WAY"`
	EditionType    int32  `json:"EDITION_TYPE"`
}
