// Code generated by excel2struct from CURRENCY_LIST.xlsx. DO NOT EDIT.
package schema

type CurrencyListDesign struct {
	Idx     int32  `json:"IDX"`  // PK
	ItemId  int32  `json:"ITEM_ID"`
	Comment string `json:"COMMENT"`
}
