// Code generated by excel2struct from ITEM_LIST.xlsx. DO NOT EDIT.
package schema

type ItemListDesign struct {
	Idx      int32  `json:"IDX"`
	ItemId   int32  `json:"ITEM_ID"`  // PK
	Comment  string `json:"COMMENT"`
	ItemType int32  `json:"ITEM_TYPE"`
}
