// Code generated by excel2struct from SHOP_LIST.xlsx. DO NOT EDIT.
package schema

type ShopListDesign struct {
	Idx        int32  `json:"IDX"`
	ShopId     int32  `json:"SHOP_ID"`  // PK
	Type       int32  `json:"TYPE"`
	OpenTime   int64  `json:"OPEN_TIME"`
	CloseTime  int64  `json:"CLOSE_TIME"`
	CurrencyId int32  `json:"CURRENCY_ID"`
	UseFlag    int32  `json:"USE_FLAG"`
	ShowFlag   int32  `json:"SHOW_FLAG"`
	Price      int32  `json:"PRICE"`
	ShopType   int32  `json:"SHOP_TYPE"`
	Ticker     int32  `json:"TICKER"`
	Comment    string `json:"COMMENT"`
}
